version: "3.9"
networks:
    internal:
        driver: bridge
services:
    nginx:
        image: nginx:latest
        networks:
            - internal
        ports:
            - 80:80
        links:
            - php-fpm
        volumes:
            - ./site:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./docker/nginx/mime.types:/etc/nginx/mime.types:ro
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - php-fpm
    php-fpm:
        build:
            dockerfile: ./docker/php-fpm/Dockerfile
        networks:
            - internal
        volumes:
            - ./site:/var/www/html
            - ./docker/php-fpm/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
        depends_on:
            - mariadb
    mariadb:
        image: mariadb:latest
        restart: always
        networks:
            - internal
        ports:
            - 3306:3306
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_MYSQL_LOCALHOST_USER: yes
            MARIADB_DATABASE: diboard_db
        volumes:
            - ./docker/mariadb/diboard_db.sql:/docker-entrypoint-initdb.d/diboard_db.sql:ro
