version: "3.9"
networks:
    internal:
        driver: bridge
services:
    nginx:
        image: nginx:latest
        networks:
            - internal
        ports:
            - 8080:80
        links:
            - php-fpm
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/error.log:/var/log/nginx/error.log
        depends_on:
            - php-fpm
    php-fpm:
        build:
            dockerfile: ./docker/php-fpm/Dockerfile
        networks:
            - internal
        volumes:
            - .:/var/www/html
        depends_on:
            - mariadb
    mariadb:
        image: mariadb:latest
        restart: always
        networks:
            - internal
        ports:
            - 3306:3306
        volumes:
            - ./docker/mariadb:/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD: root
